### ISSUE TITLE
[Amazon Linux2] username created contains dangling character "\" 

### ISSUE THREAD

**Issue by manuelfidalgo** [awsdocs/amazon-workspaces-administration-guide#10]
hi from Spain!
Iv'e configured a Linux workspace and, when prompted for a username I wrote `"qa"`, but the actual username created was `"CORP\qa"`.
The problem is that the added backslash can be annoying and make some scripts to fail. For instance, configuring a [Github Actions self-hosted runner as a service](https://docs.github.com/en/github-ae@latest/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service), fails because the service unit created uses a wrong username "CORPqa"
Is there any way of removing the "CORP\" and let the username just be "qa"?
Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
