### ISSUE TITLE
Undocumented certificate actions in access control documentation

### ISSUE THREAD

**Issue by alexpulver** [awsdocs/amazon-workspaces-administration-guide#2]
Hi,

[Control Access to Amazon WorkSpaces Resources](https://github.com/awsdocs/amazon-workspaces-administration-guide/blob/master/doc_source/workspaces-access-control.md) has an example for IAM policy to grant the user the ability to perform WorkSpaces-specific tasks except for certificate tasks. It uses the following actions: "workspaces:DeleteCertificate", "workspaces:ImportCertificate", "workspaces:DescribeCertificates".
I can't find them in the [API reference](https://docs.aws.amazon.com/workspaces/latest/api/welcome.html) - are these valid actions to use in the IAM policy?

Thanks!

**Comment by connierock** [comment]
Hi Alex ~ No, they are not valid actions to use in the IAM policy, which is why they're not in the API Reference.

Thanks,
-Connie

**Comment by 0xdabbad00** [comment]
@connierock So should the docs be changed to remove these? https://github.com/awsdocs/amazon-workspaces-administration-guide/blame/master/doc_source/workspaces-access-control.md#L136

**Comment by connierock** [comment]
Yes - I have removed them.
