### ISSUE TITLE
Clarify AWS-managed VPCs

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-workspaces-administration-guide#4]
Hello, it'd be great if the diagram displayed at:
https://docs.aws.amazon.com/workspaces/latest/adminguide/amazon-workspaces.html
would mention that the AWS-managed VPCs are still customer-owned VPCs (to differentiate from AWS services where the service is hosted in AWS-owned VPCs).
I had customer confused when looking at Workspaces documentation.

**Comment by danasch1** [comment]
Hello @wolruf. It's my understanding that your issue was resolved in email with @julieso. Let me know if anything needs to be updated.
