### ISSUE TITLE
Having multiple certificates on the smart card that can match the user.

### ISSUE THREAD

**Issue by lbrent2k** [awsdocs/amazon-workspaces-administration-guide#8]
You point out that "Having multiple certificates on the smart card that can match the user." is a common source of problems.  

If the smart card does have multiple certs, BUT the cert that WorkSpaces App asks for is indeed correct, would this STILL explain failure to accept PIN?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
